@echo off
REM Railway Environment Setup Script for Windows
REM This script generates secure environment variables for Railway deployment

echo.
echo 🚀 MedTech Backend - Railway Environment Setup
echo ==================================================
echo.

REM Generate JWT Secret Key using Python
for /f "delims=" %%i in ('python -c "import secrets; print(secrets.token_urlsafe(32))"') do set JWT_SECRET=%%i

echo 📝 Generating JWT_SECRET_KEY...
echo ✅ JWT_SECRET_KEY generated
echo.

REM Create .env.production file
(
echo # MedTech Backend - Production Environment Variables for Railway
echo # Generated: %date% %time%
echo.
echo # ===== DATABASE =====
echo # NOTE: Railway automatically sets DATABASE_URL when you add PostgreSQL service
echo # DATABASE_URL=
echo.
echo # ===== JWT Configuration =====
echo JWT_SECRET_KEY=%JWT_SECRET%
echo JWT_ALGORITHM=HS256
echo ACCESS_TOKEN_EXPIRE_MINUTES=10080
echo.
echo # ===== API Configuration =====
echo CORS_ALLOW_ORIGINS=["https://your-frontend-domain.com"]
echo.
echo # ===== GEMINI API ^(Required for prescription extraction^) =====
echo # Get your key from: https://aistudio.google.com/apikey
echo GEMINI_KEY=
echo.
echo # ===== Optional: Hugging Face Token =====
echo HF_TOKEN=
echo.
echo # ===== Optional: API Bearer Token =====
echo API_BEARER_TOKEN=
echo.
echo # ===== Application Info =====
echo APP_NAME=MedTech API
echo APP_DESCRIPTION=API for MedTech AI application
echo APP_VERSION=0.1.0
) > .env.production

echo ✅ .env.production file created!
echo.
echo 📋 ENVIRONMENT VARIABLES TO ADD TO RAILWAY:
echo ==============================================
echo.
echo Copy and paste these variables into Railway dashboard:
echo.
echo 1️⃣  JWT_SECRET_KEY:
echo    %JWT_SECRET%
echo.
echo 2️⃣  CORS_ALLOW_ORIGINS:
echo    ["https://your-frontend-domain.com"]
echo.
echo 3️⃣  GEMINI_KEY:
echo    ^<Get from https://aistudio.google.com/apikey^>
echo.
echo 4️⃣  ^(Auto-generated by Railway^)
echo    DATABASE_URL - Set automatically when you add PostgreSQL
echo.
echo ==============================================
echo.
echo 📚 Next Steps:
echo 1. Go to https://railway.app/dashboard
echo 2. Create new project from medtech-backend repo
echo 3. Add PostgreSQL service
echo 4. Copy JWT_SECRET_KEY above into Railway variables
echo 5. Add GEMINI_KEY from Google AI Studio
echo 6. Set CORS_ALLOW_ORIGINS to your frontend domain
echo 7. Enable auto-deploy on main branch
echo.
echo ✨ Setup complete! Check .env.production for reference.
echo.
pause
