#!/bin/bash
# Railway Environment Setup Script
# This script generates secure environment variables for Railway deployment

set -e

echo "🚀 MedTech Backend - Railway Environment Setup"
echo "=================================================="
echo ""

# Generate JWT Secret Key
echo "📝 Generating JWT_SECRET_KEY..."
JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
echo "✅ JWT_SECRET_KEY generated"

# Create .env.production file
cat > .env.production << EOF
# MedTech Backend - Production Environment Variables for Railway
# Generated: $(date)

# ===== DATABASE =====
# NOTE: Railway automatically sets DATABASE_URL when you add PostgreSQL service
# DATABASE_URL will be auto-generated - leave it empty here
# DATABASE_URL=

# ===== JWT Configuration =====
JWT_SECRET_KEY=$JWT_SECRET
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=$((60 * 24 * 7))

# ===== API Configuration =====
CORS_ALLOW_ORIGINS=["https://your-frontend-domain.com"]

# ===== GEMINI API (Required for prescription extraction) =====
# Get your key from: https://aistudio.google.com/apikey
GEMINI_KEY=

# ===== Optional: Hugging Face Token =====
# Only needed if using HF models
HF_TOKEN=

# ===== Optional: API Bearer Token =====
# For additional API security layer
API_BEARER_TOKEN=

# ===== Application Info =====
APP_NAME=MedTech API
APP_DESCRIPTION=API for MedTech AI application
APP_VERSION=0.1.0
EOF

echo ""
echo "✅ .env.production file created!"
echo ""
echo "📋 ENVIRONMENT VARIABLES TO ADD TO RAILWAY:"
echo "=============================================="
echo ""
echo "Copy and paste these variables into Railway dashboard:"
echo ""
echo "1️⃣  JWT_SECRET_KEY:"
echo "    $JWT_SECRET"
echo ""
echo "2️⃣  CORS_ALLOW_ORIGINS:"
echo "    [\"https://your-frontend-domain.com\"]"
echo ""
echo "3️⃣  GEMINI_KEY:"
echo "    <Get from https://aistudio.google.com/apikey>"
echo ""
echo "4️⃣  (Auto-generated by Railway)"
echo "    DATABASE_URL - Set automatically when you add PostgreSQL"
echo ""
echo "=============================================="
echo ""
echo "📚 Next Steps:"
echo "1. Go to https://railway.app/dashboard"
echo "2. Create new project from medtech-backend repo"
echo "3. Add PostgreSQL service"
echo "4. Copy JWT_SECRET_KEY above into Railway variables"
echo "5. Add GEMINI_KEY from Google AI Studio"
echo "6. Set CORS_ALLOW_ORIGINS to your frontend domain"
echo "7. Enable auto-deploy on main branch"
echo ""
echo "✨ Setup complete! Check .env.production for reference."
